version: "3"
services:
    neo4j:
        image: neo4j:5.2
        environment:
          - NEO4J_AUTH=none
        ports:
          - '7474:7474'
          - '7473:7473'
          - '7687:7687'

    web:
        build: .
        ports:
          - "3000:3000"
        depends_on:
          - neo4j
